sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8PfGkVrnMvwsV6FVW4
    access-key-secret: KbFdhj10XppHn3NbTDfFIOSW92aLTH
    bucket-name: canqiong-web
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxec14daf78de5344d
    secret: e0b4c4d66c45339b3201c842da2c65b2
